### ISSUE TITLE
Unknown Unable to verify event source

### ISSUE THREAD

**Issue by digitaljedi2** [chalfant/lambda-billing#1]
When looking at the lambda function within the AWS Console, I have ran through all the steps as explained, but in the console it says under event sources, Unable Unable to verify event source on the s3 bucket I've created.  Is this normal?

**Comment by chalfant** [comment]
I actually see the same thing in my account, even though everything is working. Is your lambda function running without errors? Are you getting records in DynamoDB?

**Comment by digitaljedi2** [comment]
Been a while, but anyhow....decided to rekindle this lambda function..
In cloudwatch logs I see the following:
Unable to import module 'index': Error at Function.Module._resolveFilename (module.js:338:15) at Function.Module._load (module.js:280:25) at Module.require (module.js:364:17) at require (module.js:380:17)

**Comment by chalfant** [comment]
Could you crack open the zip created by create_function.sh and verify that the index.js file is in it?
